#!/usr/bin/env python

__metaclass__ = type

PROJECT = 'libstepper'

class Colors:
    HEADER = '\033[95m'
    OKBLUE = '\033[94m'
    OKGREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'

class Runner:
    def __init__(self, command=None):
        self.__commands = []
        self.last = None
        self.interrupted = False
        if command != None:
            self.then(command)

    def then(self, command, stdout=True):
        self.__commands.append((command, stdout))
        return self

    def run(self):
        self.last = None
        self.interrupted = False

        import subprocess
        import os

        result = True
        for c, stdout in self.__commands:
            self.last = str(c)
            try:
                if (callable(c)):
                    result &= c()
                else:
                    call_args = c.strip().split()
                    if stdout:
                        result &= (subprocess.call(call_args) == 0)
                    else:
                        result &= (subprocess.call(call_args, stdout=open(os.devnull, 'w'), stderr=subprocess.STDOUT) == 0)
            except KeyboardInterrupt:
                # passed onto child automatically
                self.interrupted = True
                return False

            if not result:
                break
        return result


def main(all, debug, clean, test, _main, run, run_args):
    import os
    import sys
    platform = 'linux' if sys.platform in ('linux', 'linux2') else sys.platform
    which_cmd = 'where' if platform == 'win32' else 'which'

    if platform == 'win32':
        print(Colors.WARNING + Colors.UNDERLINE + 'Your current platform seems to be Windows. Project should still compile (at least the core), although it is not officially supported.' + Colors.ENDC)

    project_root = os.path.dirname(os.path.realpath(__file__))
    flavour = 'debug' if debug else 'release'
    out = os.path.join(project_root, 'out', platform, flavour)

    call = Runner()                                                                        \
        .then('{0} cmake'.format(which_cmd), stdout=False)                                 \
        .then('{0} make'.format(which_cmd), stdout=False)

    if clean:
        call.then('rm -rf {0}'.format(out))
    call                                                                                   \
        .then('mkdir -p {0}'.format(out))                                                  \
        .then(lambda: os.chdir(out) == None)                                               \
        .then('cmake -DCMAKE_BUILD_TYPE={0} {1}'.format(flavour, project_root))            \

    exes_built = []

    def core_test_name():
        return '{0}-core-test'.format(PROJECT)

    def main_demo_name():
        return '{0}-demo'.format(PROJECT)

    if all:
        call.then('make')
        exes_built.append((os.path.join(out, 'core', 'bin', core_test_name()), False))
        exes_built.append((os.path.join(out, 'bin', main_demo_name()) + ' ' + ' '.join(run_args), True))
    else:
        if test:
            call.then('make {0}-core-test'.format(PROJECT))
            exes_built.append((os.path.join(out, 'core', 'bin', core_test_name()), False))

        if _main:
            call.then('make {0}-demo'.format(PROJECT))
            exes_built.append((os.path.join(out, 'bin', main_demo_name()) + ' ' + ' '.join(run_args), True))

    if len(exes_built) == 0:
        print(Colors.WARNING + Colors.UNDERLINE + 'Warning: Only the makefiles, and no other artifacts, will be prepared. Run \'{0} -h\' to see all the options.'.format(__file__) + Colors.ENDC)
    else:
        print(Colors.OKGREEN + 'These executables will be {0} in this sequence:'.format('run' if run else 'built') + Colors.ENDC)
        for exe, as_root in exes_built:
            print(u'\u2022 {}'.format('[root] ' if as_root else '') + exe)
        print(Colors.OKGREEN + '===============================================================================' + Colors.ENDC)

    if run:
        for exe, as_root in exes_built:
            call.then(('sudo ' if as_root else '') + exe)

    succeeded = call.run()
    if not succeeded and not call.interrupted:
        print(Colors.FAIL + 'Failed to run: {}'.format(call.last) + Colors.ENDC)
    return succeeded


if __name__ == '__main__':
    import argparse
    import sys
    parser = argparse.ArgumentParser(description='builds the project')
    parser.add_argument('-a', '--all', action='store_true', help='build everything')
    parser.add_argument('-d', '--debug', action='store_true', help='build the debug flavour instead of release')
    parser.add_argument('-c', '--clean', action='store_true', help='clean the flavour\'s temporary files and the build artifacts before building')
    parser.add_argument('-t', '--test', action='store_true', help='build the cross-platform unit-tests for the core module')
    parser.add_argument('-m', '--main', action='store_true', help='build the main {} demo executable'.format(PROJECT))
    parser.add_argument('-r', '--run', action='store_true', help='run whichever executables were asked to be built after they are built (unit tests, then main exe)')
    parser.add_argument('run_args', nargs='*', help='params to pass through to the main exe, if the main exe is built, and is asked to run')
    args = parser.parse_args()
    rc = 0 if main(all=args.all, debug=args.debug, clean=args.clean, test=args.test, _main=args.main, run=args.run, run_args=args.run_args) else -1
    sys.exit(rc)
